# Travis + Tox
# Based on what I found at: https://github.com/eventlet/eventlet/blob/master/.travis.yml
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnupg2
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - make test
