# Travis + Tox
# Based on what I found at: https://github.com/eventlet/eventlet/blob/master/.travis.yml
language: python
python:
    - "2.7"
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
matrix:
    allow_failures:
        - env: TOX_ENV=py26
        - env: TOX_ENV=py33
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install tox
script:
    - tox -e $TOX_ENV
